[project]
name = "lakehouse"
version = "0.1.0"
description = "Local data lakehouse using Iceberg, DuckDB, Spark, Dagster, dbt, and Kafka"
requires-python = ">=3.14"
dependencies = [
    "duckdb>=1.4.4",
    "pandas>=3.0.1",
    "pyarrow>=23.0.1",
    "pyiceberg[duckdb,pyarrow,sql-sqlite]>=0.11.0",
]
